title: ABC Lab ELN
author: ABC Lab, UMD
logo: https://upload.wikimedia.org/wikipedia/commons/8/88/University_of_Maryland_seal.svg
parse:
  myst_enable_extensions:
    - colon_fence
    - html_image
sphinx:
  config:
    source_suffix: [".md"]
html:
  extra_static_paths: ["_static"]
  extra_js:
    - login.js
  extra_footer: ""
  extra_head: |
    <script src="https://cdn.auth0.com/js/auth0-spa-js/2.0/auth0-spa-js.production.js"></script>
    <script src="_static/auth.js"></script>

