name: 🚀 Deploy Secure Log Form

on:
  push:
    paths:
      - 'logform/**'
      - 'netlify/**'
      - 'netlify.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Inject Auth0 credentials into frontend
      - name: Inject Auth0 credentials into logform auth.js
        run: |
          sed -i 's/%%AUTH0_CLIENT_ID%%/${{ secrets.AUTH0_CLIENT_ID }}/g' logform/js/auth.js
          sed -i 's/%%AUTH0_DOMAIN%%/${{ secrets.AUTH0_DOMAIN }}/g' logform/js/auth.js

      # Deploy to Netlify
      - uses: jsmrcaga/action-netlify-deploy@v2.2.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_DEPLOY_MESSAGE: "Auto-deploy secure logform"
          build_directory: logform
          functions_directory: netlify/functions
